src/site/apt/index.apt.vm
@hboutemy 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.
- [ X] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
=> Tighten language

src/main/java/org/apache/maven/plugins/assembly/AssemblerConfigurationSource.java, src/main/java/org/apache/maven/plugins/assembly/archive/DefaultAssemblyArchiver.java, src/main/java/org/apache/maven/plugins/assembly/mojos/AbstractAssemblyMojo.java, src/test/java/org/apache/maven/plugins/assembly/archive/DefaultAssemblyArchiverTest.java, src/test/java/org/apache/maven/plugins/assembly/testutils/PojoConfigSource.java
This implements properties for assembly configuration that allow overriding UID/GID of files in TAR archive and any other archive for which plexus-archiver supports overriding of UID/GID.
[Individual …
=> MASSEMBLY-922 - allow to override UID/GID for files stored in TAR

pom.xml, src/test/java/org/apache/maven/plugins/assembly/filter/ComponentsXmlArchiverFileFilterTest.java
=> [MASSEMBLY-935] fix JDOM dependencies

src/main/java/org/apache/maven/plugins/assembly/archive/ManifestCreationFinalizer.java
=> replace deprecated manifest constructor

pom.xml, src/main/java/org/apache/maven/plugins/assembly/io/ClasspathResourceLocatorStrategy.java, src/main/java/org/apache/maven/plugins/assembly/io/DefaultAssemblyReader.java, src/main/java/org/apache/maven/plugins/assembly/io/DefaultMessageHolder.java, src/main/java/org/apache/maven/plugins/assembly/io/FileLocation.java, src/main/java/org/apache/maven/plugins/assembly/io/FileLocatorStrategy.java, src/main/java/org/apache/maven/plugins/assembly/io/Location.java, src/main/java/org/apache/maven/plugins/assembly/io/Locator.java, src/main/java/org/apache/maven/plugins/assembly/io/LocatorStrategy.java, src/main/java/org/apache/maven/plugins/assembly/io/MessageHolder.java, src/main/java/org/apache/maven/plugins/assembly/io/MessageLevels.java, src/main/java/org/apache/maven/plugins/assembly/io/MessageSink.java, src/main/java/org/apache/maven/plugins/assembly/io/PrefixedClasspathLocatorStrategy.java, src/main/java/org/apache/maven/plugins/assembly/io/URLLocation.java, src/test/java/org/apache/maven/plugins/assembly/io/PrefixedClasspathLocatorStrategyTest.java
=> remove dependency on maven-shared-io

src/site/apt/index.apt.vm
Trivial doco change, the latest xsd wasn't documented.
----
To …
=> Documentation - Add link to latest xsd

.github/workflows/maven-verify.yml
=> use shared gh action - v1

pom.xml, src/it/projects/reproducible/verify.groovy, src/main/java/org/apache/maven/plugins/assembly/filter/ComponentsXmlArchiverFileFilter.java, src/main/java/org/apache/maven/plugins/assembly/io/DefaultAssemblyReader.java, src/main/java/org/apache/maven/plugins/assembly/io/URLLocation.java, src/main/java/org/apache/maven/plugins/assembly/mojos/AbstractAssemblyMojo.java, src/main/java/org/apache/maven/plugins/assembly/repository/DefaultRepositoryAssembler.java, src/main/java/org/apache/maven/plugins/assembly/utils/AssemblyFormatUtils.java, src/test/java/org/apache/maven/plugins/assembly/archive/phase/DependencySetAssemblyPhaseTest.java, src/test/java/org/apache/maven/plugins/assembly/archive/phase/ModuleSetAssemblyPhaseTest.java, src/test/java/org/apache/maven/plugins/assembly/archive/phase/RepositoryAssemblyPhaseTest.java, src/test/java/org/apache/maven/plugins/assembly/archive/task/AddArtifactTaskTest.java, src/test/java/org/apache/maven/plugins/assembly/archive/task/AddDependencySetsTaskTest.java
Update to Java8, update dependencies, drop maven-shared-utils.
---
https://issues.apache.org/jira/browse/MASSEMBLY-959
=> [MASSEMBLY-959] Update to Java8 and drop m-shared-utils

pom.xml, src/it/projects/dependency-sets/massembly-955/pom.xml, src/it/projects/dependency-sets/massembly-955/src/main/assembly/bin.xml, src/it/projects/dependency-sets/massembly-955/verify.bsh, src/main/java/org/apache/maven/plugins/assembly/utils/FilterUtils.java, src/test/java/org/apache/maven/plugins/assembly/archive/task/AddDependencySetsTaskTest.java
Updates the maven-common-artifact-filters that brings in fix for bug.
Also bring in the related IT.
=> [MASSEMBLY-962] Update m-common-a-f to 3.3.0

pom.xml, src/test/java/org/apache/maven/plugins/assembly/format/ReaderFormatterTest.java
=> [MASSEMBLY-960] Update maven-filtering to 3.3.0

src/it/projects/bugs/massembly-964/pom.xml, src/it/projects/bugs/massembly-964/verify.groovy, src/main/java/org/apache/maven/plugins/assembly/io/FileLocation.java, src/main/java/org/apache/maven/plugins/assembly/io/URLLocation.java
method FileLocation.initFile was private and can not be override in child class
---
please ask on the …
=> [MASSEMBLY-964] Fix initFile for FileLocation, UrlLocation

pom.xml
Similar to
- https://github.com/apache/maven-remote-resources-plugin/pull/8
-----
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.
=> Fix site "usage" page

pom.xml, src/main/java/org/apache/maven/plugins/assembly/artifact/DefaultDependencyResolver.java
I dont know  if this is correct way to solve it
=> drop maven-compat - replace RepositorySystem with ArtifactFactory from core

src/site/xdoc/download.xml.vm
=> [MASSEMBLY-984] Refresh download page

pom.xml
=> [MASSEMBLY-985] Cleanup declared dependencies

src/main/java/org/apache/maven/plugins/assembly/mojos/AbstractAssemblyMojo.java
=> [MASSEMBLY-843] Make finalName parameter as writable

pom.xml, src/it/projects/reproducible/verify.groovy, src/main/java/org/apache/maven/plugins/assembly/archive/archiver/AssemblyProxyArchiver.java
uses https://github.com/codehaus-plexus/plexus-archiver/pull/271
=> [MASSEMBLY-989] apply 022 umask in RB mode

pom.xml
fix after #141 
benefits from https://github.com/codehaus-plexus/plexus-archiver/pull/273
=> Massembly 989 win

src/site/apt/examples/single/using-container-descriptor-handlers.apt.vm, src/site/apt/index.apt.vm
Add links to the `assembly-2.2.0.xsd` and `assembly-component-2.2.0.xsd`. Also fix example in `using-container-descriptor-handlers.apt.vm` to use `mdoVersion`.
[Individual Contributor License …
=> [MASSEMBLY-991] - Add links to XSDs for 2.2.0

pom.xml
=> [MASSEMBLY-997] Bump commons-io from 2.11.0 to 2.13.0

pom.xml
=> [MASSEMBLY-999] Upgrade Parent to 40

src/it/it-project-parent/pom.xml, src/it/projects/basic-features/massembly-256-pomPropertiesInterp/src/main/assembly/myassembly.xml, src/it/projects/basic-features/massembly-351-projectPrefixInterp/src/main/assembly/myassembly.xml, src/it/projects/bugs/massembly-285/massembly-285-assembly/pom.xml, src/it/projects/dependency-sets/depMgmt-override/child/src/assembly/bundle.xml, src/it/projects/multimodule/massembly-474/descriptor/pom.xml, src/it/projects/multimodule/massembly-619/descriptor/pom.xml, src/it/projects/reproducible/pom.xml
=> [MASSEMBLY-1000] ITs - cleanups, refresh plugins versions

src/main/java/org/apache/maven/plugins/assembly/AssemblerConfigurationSource.java, src/main/java/org/apache/maven/plugins/assembly/mojos/AbstractAssemblyMojo.java
=> [MASSEMBLY-1003] Remove unused remoteRepositories

src/it/projects/dependency-sets/massembly-994-refresh-unpacked/child1/pom.xml, src/it/projects/dependency-sets/massembly-994-refresh-unpacked/child1/src/main/resources/test.properties, src/it/projects/dependency-sets/massembly-994-refresh-unpacked/child2/pom.xml, src/it/projects/dependency-sets/massembly-994-refresh-unpacked/child2/src/assemble/dir.xml, src/it/projects/dependency-sets/massembly-994-refresh-unpacked/invoker.properties, src/it/projects/dependency-sets/massembly-994-refresh-unpacked/pom.xml, src/it/projects/dependency-sets/massembly-994-refresh-unpacked/verify.groovy
=> [MASSEMBLY-994] IT - refresh unpacked dependencies in dir archive

pom.xml, src/it/projects/bugs/massembly-730/pom.xml
=> [MASSEMBLY-1009] Bump commons-io from 2.13.0 to 2.15.0

pom.xml, src/main/java/org/apache/maven/plugins/assembly/filter/SimpleAggregatingDescriptorHandler.java, src/main/java/org/apache/maven/plugins/assembly/io/DefaultAssemblyReader.java, src/test/java/org/apache/maven/plugins/assembly/archive/ManifestCreationFinalizerTest.java, src/test/java/org/apache/maven/plugins/assembly/utils/LineEndingsUtilsTest.java, src/test/java/org/apache/maven/plugins/assembly/utils/LinuxLineFeedInputStreamTest.java, src/test/java/org/apache/maven/plugins/assembly/utils/WindowsLineFeedInputStreamTest.java
=> [MASSEMBLY-1010] Use IOUtils from commons-io instead of plexus

pom.xml
=> [MASSEMBLY-1011] Bump maven-archiver from 3.6.0 to 3.6.1

src/it/it-project-parent/pom.xml, src/it/projects/descriptor-refs/jar-with-dependencies/main-class-and-dependencies/pom.xml, src/it/projects/descriptor-refs/jar-with-dependencies/main-class-and-dependencies/src/main/java/test/App.java, src/it/projects/descriptor-refs/jar-with-dependencies/main-class-and-dependencies/verify.groovy
=> [MASSEMBLY-967] IT for jar-with-dependencies with main class

pom.xml, src/test/java/org/apache/maven/plugins/assembly/archive/task/AddDependencySetsTaskTest.java
=> [MASSEMBLY-1019] Maven 3.6.3 as minimum requirements

src/it/projects/bugs/massembly-1022/pom.xml, src/it/projects/bugs/massembly-1022/src/assembly/assembly.xml, src/it/projects/bugs/massembly-1022/verify.groovy, src/main/java/org/apache/maven/plugins/assembly/artifact/DefaultDependencyResolver.java, src/test/java/org/apache/maven/plugins/assembly/artifact/DefaultDependencyResolverTest.java
https://issues.apache.org/jira/browse/MASSEMBLY-1022
=> [MASSEMBLY-1022] Unresolved artifacts should be not processed
